- name: Install and Configure Nginx on 4 Servers
  hosts: web_servers
  become: true
  vars:
    # Replace with your actual values
    aws_region: "ap-south-1"
    aws_access_key: "AKIASBVB545OKIMYJ24Z"
    aws_secret_key: "dq7BriyoncYjrm6XXQ/13Xy4Krw+XHulma2bgEX2"
    s3_bucket_name: "hybbuck2"
    nginx_config_file: "/etc/nginx/nginx.conf"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install necessary packages
      package:
        name:
          - epel-release  # For Amazon Linux 2
          - nginx
        state: present
      when: ansible_os_family == 'RedHat'


    - name: Upload Nginx configuration file to S3 bucket
      aws_s3:
        bucket: "{{ s3_bucket_name }}"  # S3 bucket name
        object: "nginx.conf"            # Object key (file name) in S3 bucket
        src: "/tmp/nginx.conf"          # Source path on the control node
        mode: put                       # Specifies to upload the file
        region: "{{ aws_region }}"      # AWS region
        access_key: "{{ aws_access_key }}"  # AWS access key
        secret_key: "{{ aws_secret_key }}"  # AWS secret key


    - name: Download Nginx configuration from S3
      aws_s3:
        bucket: "{{ s3_bucket_name }}"
        object: "nginx.conf"
        dest: "/tmp/nginx.conf"
        mode: get
        region: "{{ aws_region }}"
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"

    - name: Place Nginx configuration file in the right location
      copy:
        src: /tmp/nginx.conf
        dest: "/etc/nginx/nginx.conf"
        remote_src: yes
        owner: root
        group: root
        mode: 0644
        backup: yes


    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

  tags:
    - nginx

