---
- name: Install and Configure Nginx on 4 Servers
  hosts: web_servers
  become: true
  vars:
    # Replace with your actual values
    aws_region: ap-south-1
    aws_access_key: AKIASBVB545OKIMYJ24Z
    aws_secret_key: dq7BriyoncYjrm6XXQ/13Xy4Krw+XHulma2bgEX2
    s3_bucket_name: hbuckprod
    nginx_config_file: /etc/nginx/nginx.conf
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install necessary packages
      package:
        name:
          - epel-release  # For Amazon Linux 2
          - nginx
          - python3-pip   # Install pip for Python 3
      when: ansible_os_family == 'RedHat'

    - name: Install boto3 library
      pip:
        name: boto3
        executable: pip3
      become: true


    - name: Create S3 Bucket
      aws_s3:
        bucket: "{{ s3_bucket_name }}"
        mode: create
        region: "{{ aws_credentials.region }}"
        access_key: "{{ aws_credentials.access_key }}"
        secret_key: "{{ aws_credentials.secret_key }}"
      register: s3_bucket

    - name: Fetch Nginx configuration file from master node
      fetch:
        src: /etc/nginx/nginx.conf
        dest: /tmp/nginx.conf
        flat: yes
      delegate_to: master_node
      vars:
        master_node: "{{ groups['master_nodes'][0] }}"


    - name: Download Nginx configuration from S3
      aws_s3:
        bucket: "{{ s3_bucket_name }}"
        object: "nginx.conf"
        dest: "/tmp/nginx.conf"
        mode: get
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

    - name: Place Nginx configuration file in the right location
      copy:
        src: "/tmp/nginx.conf"
        dest: "{{ nginx_config_file }}"
        owner: root
        group: root
        mode: 0644

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

  tags:
    - nginx

