---
- name: AWS S3 Bucket Upload
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Upload/PUT file to S3 bucket
      amazon.aws.aws_s3:
        profile: personal
        bucket: devopsjunction
        mode: put
        object: "2024/2/14/nginx.conf"
        src: "/etc/nginx/nginx.conf"
      register: putresult

    - debug: 
        msg: "{{ putresult.msg }} and the S3 Object URL is {{ putresult.url }}"
      when: putresult.changed

